### ISSUE TITLE
Sidebar - background click to close

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#100]
**Issue description**
A natural interaction is to click to the background out of the sidebar to close it

**Current behavior**
Close sidebar just by clicking on the X icon

**Expected behavior**
Click on the background / editor area to close sidebar

**Steps to reproduce**
Open a menu item from the sidebar

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.12.1-alpha / 592fc72

**Comment by siovene** [comment]
PR submitted to relevant third party dependency: https://github.com/arkon/ng-sidebar/pull/69

**Comment by qiuzhong** [comment]
Verified with [9df718](https://github.com/01org/zephyrjs-ide/commit/9df7180a3dd59198601120778e2669e875272d5a), this issue is not reproducible.
