### ISSUE TITLE
Misspell in GitHub login page

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#103]
**Issue description**

Misspell in GitHub login page

**Current behavior**

![selection_003](https://cloud.githubusercontent.com/assets/19813546/24544775/22706428-1637-11e7-99ae-22f18a901218.png)

**Expected behavior**

You can get your GitHub API token here .

**Steps to reproduce**

1. Click GitHub from sidebar

**'JS IDE for Zephyr OS' version:** `v0.13.0-alpha / 208a971`

**Comment by qiuzhong** [comment]
Verified with 0.13.0-alpha / [2795b54](https://github.com/01org/zephyrjs-ide/commit/2795b54b07f1ba7a44af2ddc767d374bf3f8ac75). See new screenshot:
![issue_103_fix](https://cloud.githubusercontent.com/assets/11829497/25125685/52fc28aa-2462-11e7-9fc3-aafd8cb45b2c.jpg)
