### ISSUE TITLE
No output log in console most of the time after trying to connect A101

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#104]
**Issue description**

No output log in console most of the time after trying to connect A101
**Current behavior**

No output log in console most of the time after trying to connect A101
![selection_004](https://cloud.githubusercontent.com/assets/19813546/24574711/71bc78e0-16c9-11e7-9ae0-8182b729443d.png)

**Expected behavior**

Commands list is expected each time when connect A101 after plugging or reseting
**Steps to reproduce**

1. Plug in A101 and click connect to establish connection
2. Reset A101 and click connect to establish connection

**'JS IDE for Zephyr OS' version:** `v0.13.0-alpha / 208a971`

**Comment by qiuzhong** [comment]
Sometimes executing <code>sudo service ModemManager stop</code> can fix this but it doesn't always work.

**Comment by siovene** [comment]
What about disabling ModemManager completely?

**Comment by qiuzhong** [comment]
I'll disable it completely and see if this issue still occurs in future.

**Comment by qiuzhong** [comment]
So far, I didn't encounter this issue after disabling the ModemManager with several host reboots.

@qiaojingx , please stop and disable the ModemManager service by
```
sudo systemctl stop ModemManager.service
sudo systemctl disable ModemManager.service
```
and see if this issue happens on your side?

**Comment by nagineni** [comment]
I've not seen this behavior before. Make sure that the ModemManager is disabled before you connect the device to the Host.

**Comment by qiaojingx** [comment]
Verified with commit a299ebd. This issue is not reproducible after disabling the ModemManager by rebooting.
Closed.
