### ISSUE TITLE
[update-seed] Encountered resolving symbol values statically error when start with AoT compilation

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#105]
**Issue description**

Encountered resolving symbol values statically error when start with AoT compilation

**Current behavior**

Encountered resolving symbol values statically error when start with AoT compilation
![selection_008](https://cloud.githubusercontent.com/assets/19813546/24576751/757b2190-16f4-11e7-86ea-8592d2bd4111.png)

Test environment:
![selection_009](https://cloud.githubusercontent.com/assets/19813546/24576756/88922940-16f4-11e7-853d-258dc9f0021c.png)

**Expected behavior**

Start with AoT compilation successfully.

**Steps to reproduce**

1. `$ npm run build.prod.exp` or `$ npm run build.prod.aot` or `npm run build.prod.rollup.aot`

**'JS IDE for Zephyr OS' version:** `v0.13.0-alpha / 208a971`

**Comment by qiuzhong** [comment]
Verified with 0.13.0-alpha / [2795b54](https://github.com/01org/zephyrjs-ide/commit/2795b54b07f1ba7a44af2ddc767d374bf3f8ac75). This issue is not reproducible
