### ISSUE TITLE
[update-seed] Fail to deploy the dockerized version

### ISSUE THREAD

**Issue by haoxli** [01org/zephyrjs-ide#107]
**Issue description**
Build and run the dockerized version following the README guide successfully, but http://localhost:5555 cannot access in browser.

**Current behavior**
http://localhost:5555 can’t be reached.

**Expected behavior**
http://localhost:5555 can be opened.

**Steps to reproduce**
1. Set up docker environment in Ubuntu 16.04.
2. ```git clone https://github.com/01org/zephyrjs-ide```
3. ```cd zephyrjs-ide```
4. ```git check out update-seed```
5. ```sudo docker-compose build```
<img width="348" alt="1" src="https://cloud.githubusercontent.com/assets/3271257/24938466/f9961908-1f69-11e7-9622-65386774bfb5.png">

6. ```sudo  docker-compose up -d```
![2](https://cloud.githubusercontent.com/assets/3271257/24938505/276d8c6c-1f6a-11e7-924b-a6dd574adf3a.png)

**'JS IDE for Zephyr OS' version:** `branch: update-seed / 208a971`

**Additional Information:**
Docker version: `17.03.1-ce`
Docker Compose version: `17.03.1-ce`

**Comment by haoxli** [comment]
Check logs by `docker-compose logs`:
![screenshot from 2017-04-12 12-10-29](https://cloud.githubusercontent.com/assets/3271257/24940964/3ec7846c-1f79-11e7-8951-853ea8cf06fc.png)

**Comment by siovene** [comment]
Please verify against master, as the update-seed branch was merged.

Port is now 8000, not 5555.

**Comment by haoxli** [comment]
Verified on master(commit b78ea7f), this issue cannot reproduce.
