### ISSUE TITLE
[update-seed] Access error when start angular-seed-build-prod

### ISSUE THREAD

**Issue by haoxli** [01org/zephyrjs-ide#108]
**Issue description**
Permission denied when mkdir '/home/app/angular-seed/dist/prod' in **Production build and deployment**

**Current behavior**
Access error occurs when `docker-compose -f docker-compose.production.yml up angular-seed`

**Expected behavior**
`docker-compose -f docker-compose.production.yml up angular-seed` run successfully

**Steps to reproduce**
1. Set up docker environment in Ubuntu 16.04.
2. ```git clone https://github.com/01org/zephyrjs-ide```
3. ```cd zephyrjs-ide```
4. ```git check out update-seed```
5. ```sudo docker-compose -f docker-compose.production.yml build```
6. ```sudo docker-compose -f docker-compose.production.yml up angular-seed```
![screenshot from 2017-04-12 10-30-23](https://cloud.githubusercontent.com/assets/3271257/24939883/ec4146ac-1f72-11e7-8626-2e80ee953b6f.png)

**'JS IDE for Zephyr OS' version:** `branch: update-seed / 208a971`

**Additional Information:**
Docker version: `17.03.1-ce`
Docker Compose version: `17.03.1-ce`

**Comment by siovene** [comment]
Please verify against master, as the update-seed branch was merged.

**Comment by haoxli** [comment]
Verified on master(commit b78ea7f4bdb8350864f4ae1856c9676090bcda70), this issue cannot reproduce.

**Comment by haoxli** [comment]
Hi, @siovene, this issue still can reproduce in master(commit b78ea7f4bdb8350864f4ae1856c9676090bcda70)

**Comment by qiuzhong** [comment]
Verified with [9df7180](https://github.com/01org/zephyrjs-ide/commit/9df7180a3dd59198601120778e2669e875272d5a), this issue is not reproduced.
