### ISSUE TITLE
Examples/Traffic Light is not the latest TrafficLight.js in GitHub.

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#109]
**Issue description**

Examples/Traffic Light is not the latest TrafficLight.js in GitHub.

**Current behavior**

My fork of zephyrjs is up-to-date with the upstream on the 01org organization on GitHub. How can I update examples in WebIDE?

1. Code in WebIDE/Examples/Traffic Light:
![selection_030](https://cloud.githubusercontent.com/assets/19813546/24998105/97fdd836-206b-11e7-9572-16a7977c00e9.png)

2. Code imported from GitHub is up to date with upstream :
![selection_031](https://cloud.githubusercontent.com/assets/19813546/24998126/a86c2100-206b-11e7-8e57-66cb32007d0d.png)

**Expected behavior**

It is better to keep consistent with github.

**Steps to reproduce**

1. Open WebIDE by https://01org.github.io/zephyrjs-ide/#/editor
2. Open Traffic Light from sidebar->examples->Traffic Light

**'JS IDE for Zephyr OS' version:** `v0.13.0-alpha / c60c538`

**Comment by qiaojingx** [comment]
This issue is caused by the inconsistent test code between webide(sidebar/examples/Traffic Light) and GitHub([TrafficLight.js](https://github.com/01org/zephyr.js/blob/master/samples/TrafficLight.js)). Update issue description.

**Comment by dbkinder** [comment]
BTW, this example won't work correctly in the WebIDE on a bare Arduino101 board.  As mentioned in https://github.com/01org/zephyr.js/blob/master/docs/a101_pins.md  "The flash filesystem uses SPI, so LED2 is not available when you use ashell or filesystem APIs."

**Comment by grgustaf** [comment]
Yeah, this sample should really be dropped for that reason. Too bad, I like it when it works. :)

You might want to pull samples directly from ZJS repo at the time of publishing updates to the website version of IDE? Note: I have a pending change 01org/zephyr.js#1097 that will change the GPIO open syntax so many samples will change.

**Comment by siovene** [comment]
Yeah @grgustaf, I think I'll simply reference those as a git submodule and copy them to the right place at build time.

**Comment by siovene** [comment]
Resolved.

**Comment by qiuzhong** [comment]
Verified with [3ea94bb](https://github.com/01org/zephyrjs-ide/commit/3ea94bbb6b1153fb272df8e348ad86ef429ed9a6), due to #141 and PR #145, the TrafficLight.js is not needed any more and removed.
