### ISSUE TITLE
[UI]Board Explorer Section not able to be hidden or closed

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#115]
**Issue description**
On master branch, the Board Explorer Section cannot be hidden or closed.

**Current behavior**
The Board Explorer Section is blank and it cannot be hidden or closed.

**Expected behavior**
This section should be able to be hidden or closed.

**Steps to reproduce**
1. <code>npm start</code> to launch the IDE
2. Go to http://localhost:8000/#/editor

**'JS IDE for Zephyr OS' version:** `X.Y.Z / 9df7180`
master branch

**Comment by siovene** [comment]
@clagom, is it an intended behaviour that that user should be able to close the board explorer section? I didn't infer that from the UI specs.

**Comment by clagom** [comment]
Sorry, I'm not sure to understand what the issue is here?
The board explorer section can be collapsed:
![screen shot 2017-04-27 at 15 21 31](https://cloud.githubusercontent.com/assets/1953388/25487817/3e38816e-2b5d-11e7-83b1-77de750d4285.png)
And it's never blank

**Comment by siovene** [comment]
I think the reported wants the board explorer to be closed like the Console? @qiuzhong please elaborate.

**Comment by qiuzhong** [comment]
Sorry for any misleading description.

I mean the rectangle with red border cannot be closed like the Console.
![selection_004](https://cloud.githubusercontent.com/assets/11829497/25512415/268de844-2c00-11e7-947f-9d2ceace2f0f.png)

It's from http://localhost:8000/#/editor. There is no content in this area.
When the Console area grows to its maximum, it can cover the up area. But the board explorer can not be closed.

Is the board explorer are reserved on purpose and users are allowed to close it?

**Comment by siovene** [comment]
This is the intended behavior.
