### ISSUE TITLE
Personal Github respositories not loaded for picking files

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#119]
**Issue description**
Personal Github respositories not loaded when login with Github Personal tokens.

**Current behavior**
All repositories of Otcshare orgnization are loaded.

**Expected behavior**
Your own Github repositories loaded for picking files.

**Steps to reproduce**
1. Start the IDE
2. Click Github of sidebar, input your personal Github API token
3. Otcshare respositories loaded, while they contain few files can be run in the IDE.

![issue_119](https://cloud.githubusercontent.com/assets/11829497/25526209/274bb2b2-2c45-11e7-9bbc-c581c9ed0362.png)

**'JS IDE for Zephyr OS' version:** `v0.13.2-alpha / 4aa60d3`

**Comment by qiuzhong** [comment]
I am confused: why it needs my personal Github API token but loads Otcshare projects?

**Comment by siovene** [comment]
When you create a GitHub AI token you get get to select "scopes":

![screenshot from 2017-05-02 11-04-58](https://cloud.githubusercontent.com/assets/891580/25609289/1ade9a3c-2f0e-11e7-88f4-7dd811193b5c.png)

Did you select the `repo` -> `public_repo` scope?

**Comment by qiuzhong** [comment]
I selected all the scopes:

![selection_122](https://cloud.githubusercontent.com/assets/11829497/25609528/29d72d44-2f52-11e7-9380-a275225b1cc0.png)

**Comment by qiuzhong** [comment]
Verified with [25d11ae](https://github.com/01org/zephyrjs-ide/commit/25d11ae14555e86513a69d180a56526db2fbb6f0), this issue is not reproducible. All personal repositories can be loaded for picking files now.
