### ISSUE TITLE
[REG] Multiple tabs are still allowed to connect to the same device

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#120]
**Issue description**
<strong>Connect</strong> button is not disabled for a second tab. 

**Current behavior**
The <strong>Connect</strong> button for a second tab is not disabled if the device is connected in one tab. 

**Expected behavior**
If one tab is connect to the board, any other tabs are not allowed to connect the same device: the <strong>Connect</strong> should be disabled.

**Steps to reproduce**
1. Launch to IDE and go to http://localhost:8000/#/editor 
2. Open two tabs
3. Switch to tab 1, connect to the device and <strong>Connect</strong> is disabled. 
4. Switch to tab 2, <strong>Connect</strong> is still enabled. But if you try connecting to connect the same device in tab 2, you'll get an <strong>Connected failed</strong> alert.

![selection_009](https://cloud.githubusercontent.com/assets/11829497/25605136/5eba9f12-2f3b-11e7-8170-d6cf670c133d.png)
![selection_012](https://cloud.githubusercontent.com/assets/11829497/25605424/441eb97a-2f3d-11e7-9506-4cdeef755fdd.png)
![issue_120](https://cloud.githubusercontent.com/assets/11829497/25605587/6012a3d4-2f3e-11e7-8180-0534ccd980fc.png)
![selection_010](https://cloud.githubusercontent.com/assets/11829497/25605745/b9881aa6-2f3f-11e7-8a51-3aa282fecede.png)

**'JS IDE for Zephyr OS' version:** ` v0.13.2-alpha / de80886`

**Comment by siovene** [comment]
This is fine. You can also click on Connect if no devices at all are connected. I don't see this as a usability issue. You might even first click on Connect, then see the browser window for  he device selection (that says "no devices"), then physically connect a device, then select it from the list when it appears, and continue.
