### ISSUE TITLE
Change the Arduino 101 board with no logomarks

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#123]
**Issue description**
For license issue we cannot display any logomarks on the board, attaching this one to replace the one online
[genuino101.svg.zip](https://github.com/01org/zephyrjs-ide/files/970996/genuino101.svg.zip)

**Current behavior**
We display several registered trademarks

**Expected behavior**
Version of the board without logos

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.13.2-alpha / 8050eef

**Comment by siovene** [comment]
I'll close this manually as it's implemented in the `board-viewer` branch.
