### ISSUE TITLE
Misalignment in the landing page / buttons

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#124]
**Issue description**
P.S. I see there's a misalignment now between the title/mark and the call to action buttons below:
![9d550f5c-2f52-11e7-84e3-ea6a115677ef](https://cloud.githubusercontent.com/assets/1953388/25656648/fc314b5e-2ff1-11e7-87e3-f09357d3c8e5.png)

**Current behavior**
ul, menu, dir {
    display: block;
    list-style-type: disc;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 0px;
    -webkit-margin-end: 0px;
    -webkit-padding-start: 40px; **< this is what cause the misalignment** 
}

**Expected behavior**
With this CSS modifications it seems fixed:
<img width="1371" alt="screen shot 2017-05-03 at 11 14 43" src="https://cloud.githubusercontent.com/assets/1953388/25656658/0a0d412e-2ff2-11e7-9b93-e1eb6f293025.png">

**Steps to reproduce**
Landing page

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.13.2-alpha / 8050eef

**Comment by siovene** [comment]
As I was commenting in #122, I frankly don't like this solution. Even tho the menubar block is now center-aligned with the app's name above, my eyes seem to see the text and almost ignore the `>` symbols. So, if I focus, I can see that the alignment is correct, but at a first glance it seems that the menubar is too much to the left.

Can we get rid of the `>` symbols so the flow is more natural?

**Comment by clagom** [comment]
We could put the > closer to the labels, so the block would be always centred but a bit more compact. I think as first step solution this might be ok, then we can think of redesigning the CTAs without > and with other visual solution. At the moment if we just remove the arrows > it looks weak and doesn't highlight the call to actions effectively.

**Comment by siovene** [comment]
I still think it looks slanted. What about making them buttons with a background? That would settle the alignment because the eyes would look at the buttons as whole.

**Comment by clagom** [comment]
I don't think this is a final solution, but if you prefer this version to the previous proposal then let's go on with buttons for now while we work on a better visual:

<img width="803" alt="screen shot 2017-05-03 at 12 06 11" src="https://cloud.githubusercontent.com/assets/1953388/25658089/eed55156-2ff8-11e7-9c3c-ea12562c4605.png">

<img width="968" alt="screen shot 2017-05-03 at 12 03 58" src="https://cloud.githubusercontent.com/assets/1953388/25658035/bd484aee-2ff8-11e7-98db-b56538a5e962.png">
