### ISSUE TITLE
Failed to update webdriver on Windows

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#129]
**Issue description**
Failed to update webdriver before running e2e tests

**Current behavior**
When running <code>npm run webdriver-update</code> to update webdriver, it fails.

**Expected behavior**
Run <code>npm run webdriver-update</code> without errors and all webdriver packages download.

**Steps to reproduce**
1. <code>git clone https://github.com/01org/zephyrjs-ide.git</code>
2. <code>cd zephyrjs-ide && npm install</code>
3. <code>npm install webdriver-manager && npm run webdriver-update</code>
```
C:\Workspace\verification\zephyrjs-ide>npm run webdriver-update

> zephyrjs-ide@0.13.2-alpha webdriver-update C:\Workspace\verification\zephyrjs-
ide
> node_modules/protractor/bin/webdriver-manager update

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
...
```

**'JS IDE for Zephyr OS' version:** `0.13.2-alpha / c013aaf`

**Others information**
Reproduced on Windows 8.1 & Windows 10

**Comment by siovene** [comment]
Maybe try with PowerShell? The CI script works on appveyor: https://ci.appveyor.com/project/siovene/zephyrjs-ide/branch/master

**Comment by qiuzhong** [comment]
This issue still remains in PowerShell on Windows:
```
PS C:\Workspace\verification\zephyrjs-ide> npm run webdriver-update

> zephyrjs-ide@0.13.2-alpha webdriver-update C:\Workspace\verification\zephyrjs-ide
> node_modules/protractor/bin/webdriver-manager update

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

This issue happens when running <code>npm run webdriver-update</code> solely. But I didn't find this command was running from the CI log.

The [npm scripts webdriver-update](https://github.com/01org/zephyrjs-ide/blob/master/package.json#L42) is defined as:
```
"webdriver-update": "node_modules/protractor/bin/webdriver-manager update",
```
It works well on Linux but fails on Windows.

**Comment by siovene** [comment]
Does the same happen with upstream angular-seed? https://github.com/mgechev/angular-seed

**Comment by qiuzhong** [comment]
Tried with angular-seed.
This issue also exists in the upstream angular-seed.

**Comment by siovene** [comment]
Then please report a bug there, that would be great.

**Comment by qiuzhong** [comment]
New issue filed at upstream angular-seed, see [#1926](https://github.com/mgechev/angular-seed/issues/1926)

**Comment by qiuzhong** [comment]
Upstream angular-seed had fixed this issue.

**Comment by siovene** [comment]
Upstream merged.
