### ISSUE TITLE
Add capability to save files to the device as well

### ISSUE THREAD

**Issue by poussa** [01org/zephyrjs-ide#133]
**Issue description**
Enhance the file save dialog by adding a checkbox which allows to save the file to the device too.

**Current behavior**
Saves the file to the browser local storage only. The only way to save files to the device is to use the cumbersome ashell "load" command, which we should get rid of.

**Expected behavior**
Being able to save files to the device. For example, configuration files for the app, like data.json which the application would read and act accordingly. One use case is the pattern matching engine (PME) neuron configuration which can be generated by using an external tool, saved to the device and use a JS app to program the PME.

**Steps to reproduce**
Not possible

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.13.2-alpha / 8050eef

**Comment by nagineni** [comment]
I have the changes that are needed to transfer and save the file on the device. I can provide the patch when the UI is ready so that we can hook the parts together.
