### ISSUE TITLE
Board explorer disappeared

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#136]
**Issue description**
The content of the board explorer disappeared

**Current behavior**
Empty content
![screen shot 2017-05-11 at 16 08 58](https://cloud.githubusercontent.com/assets/1953388/25956689/49fd2326-3664-11e7-8c80-411e42f2dec5.png)

**Expected behavior**
The board explorer should display the board

**Steps to reproduce**
Editor

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.14.0-alpha / cedbf16

**Comment by siovene** [comment]
Looks like I built the wrong branch, will fix soon.

**Comment by siovene** [comment]
Done.
