### ISSUE TITLE
[minor] Text unreadable on file selection panes

### ISSUE THREAD

**Issue by grgustaf** [01org/zephyrjs-ide#142]
**Issue description**
I think this is due to a recent update. When you click on Files or Examples, the text in the pane that opens listing the files is black on a dark grey background, and very hard to read.

I'm seeing this on Chrome 58 on Ubuntu 16.04.

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.15.0-alpha / efbd106

**Comment by siovene** [comment]
If I'm seeing this right, this is only on mouse-hover, right?

**Comment by grgustaf** [comment]
You're right, I forgot that when I went to write it. :)

**Comment by qiuzhong** [comment]
Verified with [3ea94bb](https://github.com/01org/zephyrjs-ide/commit/3ea94bbb6b1153fb272df8e348ad86ef429ed9a6), this issue has been fixed. Here is the effect:

![142](https://cloud.githubusercontent.com/assets/11829497/26230101/08c75a1e-3c79-11e7-80a4-3516f0606b2f.png)
