### ISSUE TITLE
IDE Ihex strings stripping out comments also removes URL beginning with http:// or https://

### ISSUE THREAD

**Issue by jimmy-huang** [01org/zephyrjs-ide#143]
The IDE default strips out comments and blank spaces in the JS file when converting it to ihex, but the function stripComments() also strips out valid URL strings that contains "http://" or "https://", this causes samples like SensorBLEDemo.js to break.

**Comment by qiuzhong** [comment]
Verified with [3ea94bb](https://github.com/01org/zephyrjs-ide/commit/3ea94bbb6b1153fb272df8e348ad86ef429ed9a6), this issue is not reproducible.
