### ISSUE TITLE
Broken layout on the Board Explorer

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#158]
**Issue description**
The layout of the board explorer appears broken once you start interacting with it

**Current behavior**
Interaction breaks the layout of the board explorer

**Expected behavior**
I know we are going to rewrite the board explorer altogether, but at the moment is very broken. I wonder if there's a quick fix for the layout? Or we could prioritize the new board explorer.
![screen shot 2017-05-31 at 16 36 48](https://cloud.githubusercontent.com/assets/1953388/26640411/8ec5c2ae-461f-11e7-8717-f8b718d14290.png)

The issue is not related to the size of the window or column.

**Steps to reproduce**
Click on the board

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.15.3-alpha / 6a05dff

**Comment by clagom** [comment]
Might be better also to link/use this Genuino 101 board from the Board Explorer repositories directly: https://github.com/Board-Explorer/board-explorer/tree/master/boards/arduino_101

**Comment by siovene** [comment]
No point in submitting issues for the board viewer as the whole thing is going to be replaced with a new implementation. (BTW this works fine for me on Chrome)
