### ISSUE TITLE
Editor and home component e2e tests failed

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#163]
**Issue description**
All the editor and home component e2e tests failed.

**Current behavior**
The error log shows the element cannot be located any more when running editor and home component e2e tests.

**Expected behavior**
All the e2e tests pass

**Steps to reproduce**
1. `git clone https://github.com/01org/zephyrjs-ide`
2. `cd zephyrjs-ide && npm install`
3. In terminal 1, `npm run serve.e2e`
4. In terminal 2, `npm run e2e`

See the detailed e2e error log:
[e2e_test_log.txt](https://github.com/01org/zephyrjs-ide/files/1067779/e2e_test_log.txt)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.16.0-alpha / 1c60c6f`
Chrome version: 59.0.3071.86

**Comment by siovene** [comment]
- Does this have a 100% failure rate? Because CI on Appveyor is fine: https://ci.appveyor.com/project/siovene/zephyrjs-ide/branch/master
- What about simply `npm run e2e.ci`?

**Comment by qiuzhong** [comment]
1. Yes. It happend on Ubuntu/Fedora/Windows 8.1/Windows 10.
2. Simply `npm run e2e.ci` can get all e2e tests passed. It seems that `npm run e2e.ci` builds **prod** e2e test code while `npm run serve.e2e` builds **dev** one.

**Comment by qiuzhong** [comment]
Verified with `v0.17.0-alpha / 292ef61`. This is not reproducible: all the e2e tests can get through.
