### ISSUE TITLE
Sidebar titles consistency

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#164]
**Issue description**
At the moment only GitHub in the sidebar has a title, for consistency I would add titles also to the other categories:
![screen shot 2017-06-13 at 11 04 35](https://user-images.githubusercontent.com/1953388/27077527-4464b6a8-5028-11e7-8491-34efa53c21e2.png)
![screen shot 2017-06-13 at 11 04 39](https://user-images.githubusercontent.com/1953388/27077529-45e131c8-5028-11e7-8be6-814418248869.png)

Same font/font-size

**Current behavior**
No titles

**Expected behavior**
With titles

**Steps to reproduce**
-

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.15.3-alpha / 6a05dff

**Comment by qiuzhong** [comment]
Verified with `v0.18.2-alpha / 1400438`, good to see every sidebar item has a title now for consistency.
