### ISSUE TITLE
Feature: add Settings UI

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#165]
**Issue description**
Sent screens:
![settings01](https://user-images.githubusercontent.com/1953388/27078811-10332dce-502d-11e7-8239-91309a0245e1.png)
![settings02](https://user-images.githubusercontent.com/1953388/27078813-11cd2a9a-502d-11e7-992e-430b80d51ced.png)
Settings icon from Font-Awesome

**Current behavior**
none

**Expected behavior**
Mock-up

**Steps to reproduce**
-

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.15.3-alpha / 6a05dff

**Comment by siovene** [comment]
Added initial implementation with "Font size" setting. More settings will be added in time.

**Comment by xiaoyu3x** [comment]
Verified with v0.18.3-alpha / c803caa, "Font size" and "Line numbers" function work well.
