### ISSUE TITLE
Most joule_570x board view components are not clickable

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#169]
**Issue description**
When the Joule board is selected, most of its components are not clickable. J1 and J4 components can be clicked. But J1Pin1~J1Pin6 are obviously mapped incorrectly (All are mapped to DC Jack while it's already been mapped to J4).

**Current behavior**
Most components are not clickable.

**Expected behavior**
The Joule board view components are mapped correctly and function well.

**Steps to reproduce**
1. Launch IDE.
2. Select **The Intel® IoT Developer Kit for the Intel® Joule™ module**.
3. Check the board view and click some components.

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.18.2-alpha / 1400438`

**Comment by siovene** [comment]
I would say that we track this sort of things with #170. It's not actually a bug with the IDE, but simply missing information in the files that I got form the board-explorer project.
