### ISSUE TITLE
Multiple tabs connected to a device mess up the console output

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#17]
**Issue description**

Multiple tabs connected to a device mess up the console output

**Current behavior**

When you connect multiple tabs to the same device, the console output gets messed up with seemingly random characters appearing. Things still appear to be working fine tho.

**Expected behavior**

Each console should be truly independent.

**Steps to reproduce**

Connect multiple tabs to the same device and do some operations in the consoles.

**Zephyr.js IDE version:** `v0.4.0 / 2643032`

**Comment by siovene** [comment]
Resolved by not allowing multiple concurrent connections to the same device.

**Comment by qiuzhong** [comment]
Tested and verified with [de80886](https://github.com/01org/zephyrjs-ide/commit/de80886d9d8ca9f43c09710754353996640177cd), the console output messing up issue is not reproducible. But multiple tabs are still allowed to connect to the same device. See [issue#120](https://github.com/01org/zephyrjs-ide/issues/120).
