### ISSUE TITLE
Information of some board components is missing

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#170]
**Issue description**
Information of some board components is missing. Their detailed information is not complete when clicking them. Either component or description or both values are empty. This exists in the **minnowboard_turbot_B_41** / **quark_mcu_dev_kit_c1000** / **quark_mcu_dev_kit_d2000** boards so far.

**Current behavior**
Some component information is not complete.

**Expected behavior**
All clickable components information is complete.

**Steps to reproduce**
1. Launch IDE
2. Select **Minnowboard** / **C1000** / **D2000** board respectively.
3. Check the components, click them and check the detailed information.

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.18.2-alpha / 1400438`

**Comment by siovene** [comment]
@poussa, can we get the data files (SVG, JSON, MD docs) from the Board Explorer project to be:

1. in a dedicated repository
2. updated and maintained?

**Comment by qiuzhong** [comment]
Some information is still missing. For example, Select **C1000** board and click **BLE**:
![170](https://user-images.githubusercontent.com/11829497/28904337-c9b5cc20-783c-11e7-9057-4eeb5033a2ff.png)
