### ISSUE TITLE
Grove LCD can't work

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyrjs-ide#176]
**Issue description**
Grove LCD can't work normally on ide.

**Current behavior**
Error throws when invoking zjs_glcd_call_remote_function() api.
`src/zjs_grove_lcd_ipm.c:63 zjs_glcd_call_remote_function():
(error) error code:1
Error:error received`

**Expected behavior**
Grove LCD works normally and shows "Counter:1...".

**Steps to reproduce**
1.Connect grove lcd and Arduino 101 board.
2.Flash ide into 101 board, build and run ide.
3.Copy [GroveLCD.js](https://github.com/01org/zephyr.js/blob/master/samples/GroveLCD.js) to IDE and run it.

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.18.3-alpha / 92f2e6b

**Comment by siovene** [comment]
Please report this against the zephyr.js project. Thanks!
