### ISSUE TITLE
Redundant character '{small}' appears

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyrjs-ide#177]
**Issue description**
On the description page of Intel MinnowBoard Turbot B41 , {small} presents at the end of each paragraph.

**Current behavior**
Redundant character '{small}' appears on the description  page of Intel MinnowBoard Turbot B41.

**Expected behavior**
There aren't {small} on Intel MinnowBoard Turbot B41 page.

**Steps to reproduce**
1.Launch the IDE and go to http://localhost:8000/#/editor.
2.Select "Intel MinnowBoard Turbot B41" in the drop-down list "Select board".
3.Click circle "i" next to "Select board".
![screenshot](https://user-images.githubusercontent.com/17694094/28562328-638ab0d0-7154-11e7-8855-d0400e6f41ed.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.18.3-alpha / c803caa`

**Comment by qiuzhong** [comment]
Verified with [2d0169](https://github.com/01org/zephyrjs-ide/commit/2d0169c6ffbe6c99a8c71024d1b16cdaa279d34f), this issue has been fixed.
