### ISSUE TITLE
Links of "Learn More:MinnowBoard Turbot" and "High Speed Expansion" are invalid

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyrjs-ide#178]
**Issue description**
"Learn More:MinnowBoard Turbot" and "High Speed Expansion" can't open relative webpage on the description page of Intel MinnowBoard Turbot B41.

**Current behavior**
"http://localhost:8000" popups when accessing "Learn More:MinnowBoard Turbot" and "High Speed Expansion" links.

**Expected behavior**
Relative webpages popup when accessing "Learn More:MinnowBoard Turbot" and "High Speed Expansion". 

**Steps to reproduce**
1.Launch the IDE and go to http://localhost:8000/#/editor.
2.Select "Intel MinnowBoard Turbot B41" in the drop-down list "Select board".
3.Click circle "i" next to "Select board".
4.Click links of  "Learn More:MinnowBoard Turbot" and "High Speed Expansion".
![screenshot](https://user-images.githubusercontent.com/17694094/28562671-cd9eeb7a-7155-11e7-8df1-fc9d1984d607.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.18.3-alpha / c803caa`

**Comment by qiuzhong** [comment]
Verified with [2d0169c](https://github.com/01org/zephyrjs-ide/commit/2d0169c6ffbe6c99a8c71024d1b16cdaa279d34f), the link issues have been fixed.
