### ISSUE TITLE
Home page features displaying

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#181]
**Issue description**
There is a tiny typo in home page features and feature items are not listed well.

**Current behavior**
Feature items are not listed well.

**Expected behavior**
Feature items are listed like this:
```
* Plug-and-play WebUSB connectivity
* JavaScript Runtime for Zephyr® OS powered boards
* Instant JAvaScript code execution on target
* IDE with multiple tabs, console shell, and GitHub integration
* Web app that works online and offline
* Integrated documentation and board explorer
```

**Steps to reproduce**
Start the IDE and go to home page.
![181](https://user-images.githubusercontent.com/11829497/28859442-d4ec47e4-7789-11e7-8ff4-27bf88aa5185.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.19.0-alpha / 18c7815`

**Comment by siovene** [comment]
The list lacks list indicators (*) by design, but I will fix the typo. Thanks!

**Comment by qiuzhong** [comment]
Verified with [4f773db](https://github.com/01org/zephyrjs-ide/commit/4f773db810effa4748bc9158f2e3adeeddf8445f), typo fixed.
