### ISSUE TITLE
Find typo in home page

### ISSUE THREAD

**Issue by canxcao** [01org/zephyrjs-ide#186]
**Issue description**
Find typo in home page

**Current behavior**
1. "Plug in your USB cable ro ....", the "ro" is misunderstand.
2. "Theis wiki is....", the "Theis" is same as above.

**Expected behavior**
I think change the word "ro" to "to", "Theis" to "The" or "This" will be better.

**Steps to reproduce**
1. Launch the IDE and go to http://localhost:8000
2. Check the description of "02.CONNECT THE BOARD",
3. Check the description of "ZJS IDE tutorial",

**'JS IDE for Zephyr OS' version: v0.20.0-alpha/ 4f773db

**Comment by xiaoyu3x** [comment]
Verified with [ae6c496](https://github.com/01org/zephyrjs-ide/commit/ae6c49681b0dfa4a631359998f11c7587f0d758e), typo fixed.
