### ISSUE TITLE
The shortcut key is missing in contextmenu

### ISSUE THREAD

**Issue by xiaoyu3x** [01org/zephyrjs-ide#189]
**Issue description**
The shortcut key of "Cut" and "Copy" aren't showed in editor windows's contextmenu.

**Current behavior**
The shortcut key of "Cut" and "Copy" aren't showed in editor windows's contextmenu.

**Expected behavior**
"Ctrl+x" is showed as the shortcut key of "Cut".
"Ctrl+c" is showed as the shortcut key of "Copy".

**Steps to reproduce**
Start the IDE and enter editor window.
![capture3](https://user-images.githubusercontent.com/17694094/29303401-199a6e04-81bf-11e7-8158-f9391b881283.PNG)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.21.0-alpha / e45579c`

**Comment by siovene** [comment]
This is how Monaco Editor does it and we can't change. To the best of my guessing, this is because Copy/Cut/Paste use the system clipboard, so the shortcuts of the underlying OS apply.
