### ISSUE TITLE
Tweak on the Board Explorer modal window

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#192]
**Issue description**
A first step / easy tweak to improve the current modal window that opens over the whole area of the editor could be to include it within the area of the board itself.

**Current behavior**
Modal window over the whole editor page

**Expected behavior**
![mockup](https://user-images.githubusercontent.com/1953388/30965065-df400df4-a44b-11e7-8437-958d7e44d023.jpg)

**Steps to reproduce**
Click on a element of the board

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.21.0-alpha / ebd6de1

**Comment by xiaoyu3x** [comment]
This issue isn't produced with commit [3ca5e23](https://github.com/01org/zephyrjs-ide/commit/3ca5e23effd1ef9dddcfa49a963c660fd225cf0a)
