### ISSUE TITLE
Editor on Safari shows another tab on the right

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#25]
**Issue description**
On Safari another tab on the right column appears. These tabs on the right look inconsistent with the ones on the left column
![screen shot 2017-02-01 at 10 35 21](https://cloud.githubusercontent.com/assets/1953388/22503584/5a07cd86-e86a-11e6-8d63-416ba6344e20.png)

**Current behavior**
Different looking tabs, and the mouse over changes the size of the font, with underlining the text:
![screen shot 2017-02-01 at 10 35 32](https://cloud.githubusercontent.com/assets/1953388/22503582/57b2dbc0-e86a-11e6-98eb-5185d241a0cc.png)

The button also could be more similar to the "+ New Sketch" button on the left side (e.g. with dark text):
![screen shot 2017-02-01 at 10 38 42](https://cloud.githubusercontent.com/assets/1953388/22503666/ad437f2c-e86a-11e6-9ded-c78e74e22e02.png)

**Expected behavior**
Consistent looking tabs and text, mouse over links behaviour

**Steps to reproduce**
Using Safari or Firefox

**Zephyr.js IDE version:** `X.Y.Z / abcd1234`
Zephyr.js IDE / v0.5.0 / 8ae1482

**Comment by siovene** [comment]
Yes, it is. I will publish the OCF Explorer soon and then it would be great if you could offer feedback on the UI/UX.
