### ISSUE TITLE
Add ability to rename tabs at will

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#32]
**Issue description**

Tab names are currently fixed.

**Current behavior**

Tab names cannot be edited.

**Expected behavior**

Tab names should be edited in place.

**Zephyr.js IDE version:** `0.5.0`

**Comment by clagom** [comment]
Maybe we can do this with right click? Or double click on the name text.

**Comment by siovene** [comment]
Right click is weird, it's not common to "steal" the context menu in the browser. Double-click is okay but it's hard to find. What about a small edit icon (a pencil) next to the close tab button, that appears only if the tab is hovered?

**Comment by clagom** [comment]
That would be fine as well
