### ISSUE TITLE
Add instructions about how to flash a device to work with the IDE

### ISSUE THREAD

**Issue by baleboy** [01org/zephyrjs-ide#37]
**Issue description**

Users need documentation about what devices are supported and how they should be configured. This could be in the About page, or some other documentation page if it makes sense. The starting point can be found at https://github.com/01org/zephyr.js/blob/master/docs/ashell.md

**Zephyr.js IDE version:** `X.Y.Z / abcd1234`
v0.5.0 / cf328b3

**Comment by clagom** [comment]
+1 in the "About" page

**Comment by xiaoyu3x** [comment]
This issue isn't produced with commit [3ca5e23](https://github.com/01org/zephyrjs-ide/commit/3ca5e23effd1ef9dddcfa49a963c660fd225cf0a)
