### ISSUE TITLE
The popup dialogs are below other UI elements

### ISSUE THREAD

**Issue by kenchris** [01org/zephyrjs-ide#41]
The popup dialogs are below other UI elements:

![screenshot from 2017-02-09 15-01-29](https://cloud.githubusercontent.com/assets/1101339/22822393/96bc1cd4-ef7f-11e6-8084-c907d3eab218.png)

**Comment by qiaojingx** [comment]
Verified with **JS IDE FOR ZEPHYR OS** / v0.8.3-alpha / be5c388
This issue is not reproducible.
