### ISSUE TITLE
Add staying connected to USB device

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyrjs-ide#44]
**Issue description**
When input 'reboot' command, zephyr.js IDE does not stay connected to USB device

**Current behavior**
not stay connected to USB device

**Expected behavior**
stay connected to USB device

**Steps to reproduce**
input 'reboot' command in CONSOLE windows by zephyr.js IDE

**Zephyr.js IDE version:** `0.6.2 / 88b29683`

**Comment by siovene** [comment]
This is impossible to implement because the connection is reset when a reboot happens (obviously) and a new connection cannot only be created with manual input from the user, otherwise Chrome will complain about a security error.
