### ISSUE TITLE
Console windows will be locked

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyrjs-ide#45]
**Issue description**
when drag console windows up and release, this windows will be locked and pick up never

**Current behavior**
be locked and never pick up

**Steps to reproduce**
drag console windows up and release

**Zephyr.js IDE version:** `0.6.2 / 88b29683`

**Comment by siovene** [comment]
I'm sorry but I don't understand the issue description... can you please elaborate?

I assume by "drag" you mean that you are resizing the Console window? Then you make it bigger and then release? And then what happens?

**Comment by cuiyanx** [comment]
yes, resizing the Console window, this window will be bigger, and release it. you will see that window will be locked and never pick up.

**Comment by siovene** [comment]
Can you please explain what you mean by "locked" and "never pick up"?

**Comment by haoxli** [comment]
I think the screenshots will help to understand easier.
<img width="378" alt="1" src="https://cloud.githubusercontent.com/assets/3271257/22935580/f257fa68-f30d-11e6-838d-b0101e260a9f.PNG">
After drag the button up, it will disappear, the console window will be locked, and cannot be resized.
<img width="398" alt="2" src="https://cloud.githubusercontent.com/assets/3271257/22935868/cb2d1a4e-f30e-11e6-97e9-d1e223ae8c1d.PNG">

**Comment by siovene** [comment]
Okay, thanks, I could reproduce it. I'll look into it.

**Comment by qiaojingx** [comment]
Verified with **JS IDE FOR ZEPHYR OS** / v0.8.3-alpha / be5c388
This issue is not reproducible.
