### ISSUE TITLE
Covering each other by console logs

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyrjs-ide#46]
**Issue description**
When upload JS code, this code will run automatically on USB device, but console logs will be covered each other.

**Current behavior**
console logs will be covered each other

**Expected behavior**
console logs will be displayed line by line 

**Steps to reproduce**
upload JS code

**Zephyr.js IDE version:** `0.6.2 / 88b29683`

**Comment by qiaojingx** [comment]
Verified with **JS IDE FOR ZEPHYR OS** / v0.8.3-alpha / be5c388
This issue is not reproducible.
