### ISSUE TITLE
Messy code print in console window

### ISSUE THREAD

**Issue by cuiyanx** [01org/zephyrjs-ide#48]
**Issue description**
There are confusion about console logs and commands in the console window when switch between "About" tab and "Editor" tab. The same situation has been happened when close and create "TAB#1".

**Current behavior**
Display confusion
![selection_008](https://cloud.githubusercontent.com/assets/22387607/23058982/616f8d46-f532-11e6-8ff3-e632b9909ec1.png)

**Expected behavior**
correct print in console window

**Steps to reproduce**
```
1.Connect to USB device
2.Click on "About" tab
3.Click on "Editor" tab and will be disconnect to USB device
4.Connect to USB device again
5.Input ashell command in console window.
```
or
```
1. Connect to USB device with "TAB#1" 
2. Closed the "TAB#1" and will create new "TAB#1"
3. Connect again to USB device with new "TAB#1" 
4. Input ashell command in console window.
```

**Zephyr.js IDE version:** `v0.8.3-alpha / be5c388`

**Comment by cuiyanx** [comment]
@siovene Maybe this issue is the same as #17 , I'm not really sure.

**Comment by siovene** [comment]
@cuiyanx it's possible... I will confirm when I take a closer look, thanks!

**Comment by siovene** [comment]
I can't reproduce this anymore in current master.

**Comment by qiuzhong** [comment]
I can't reproduce this issue either ([c013aaf](https://github.com/01org/zephyrjs-ide/commit/c013aaf852ffdae0b7fc0d3e5d9cea6c8e217bfb))
