### ISSUE TITLE
Loading of the website

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#51]
**Issue description**
Now the loading is quite uninspiring:
![screen shot 2017-02-16 at 11 30 08](https://cloud.githubusercontent.com/assets/1953388/23019648/47d79542-f43b-11e6-8d40-58c191af4a63.png)

**Current behavior**
Word "loading..." top left of a white page

**Expected behavior**
![example](https://cloud.githubusercontent.com/assets/1953388/23019785/ef36f92c-f43b-11e6-99fe-375ff630c1f4.jpg)
Spinning icon with text, all centred in the middle of the page, the background colour can be: #3B404B
We can use any ready-to-use icon, it's ok if simple and similar to the one in the example.

**Steps to reproduce**

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`

ZEPHYR.JS IDE / v0.6.0-alpha / 2f9df32

**Comment by qiaojingx** [comment]
Verified with **JS IDE FOR ZEPHYR OS** / v0.8.3-alpha / be5c388
This issue is not reproducible.
