### ISSUE TITLE
[UI] Layout disorder when resize widnows

### ISSUE THREAD

**Issue by haoxli** [01org/zephyrjs-ide#52]
**Issue description**
When resize 'Console' window and 'Board schematic' window together for twice, widows layout will disorder.

**Current behavior**
The 'Board schematic' window is under the ‘Console’ window

**Expected behavior**
The 'Board schematic' window is still on the  the right of  ‘Tab’ window

**Steps to reproduce**
1. Resize 'Board schematic' window using resize handle 
<img width="959" alt="1" src="https://cloud.githubusercontent.com/assets/3271257/23056817/2b9fb4b6-f528-11e6-9b3d-1356c7a6b110.PNG">

2. Resize 'Console' window using resize handle to minimum
<img width="974" alt="2" src="https://cloud.githubusercontent.com/assets/3271257/23056861/5d806dfe-f528-11e6-8d6d-5493745e154e.PNG">

3. Follow the steps again. 

4. The 'Board schematic' window will disorder
<img width="948" alt="3" src="https://cloud.githubusercontent.com/assets/3271257/23056896/8fcb687c-f528-11e6-9099-bb5f99034df0.PNG">

**'JS IDE for Zephyr OS' version:** `0.8.3-alpha`

**Comment by qiaojingx** [comment]
Verified with JS IDE FOR ZEPHYR OS / v0.9.0-alpha / 20f3dac
The layout of window is updated. This issue is not reproducible.
