### ISSUE TITLE
OFC Explorer - Consistent visual design

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#57]
**Issue description**
At the moment the OFC Explorer has a different visual comparing to the rest of the UI

**Current behavior**
Inconsistency 

**Expected behavior**
![zephyros_notification explorer_tweaks 1](https://cloud.githubusercontent.com/assets/1953388/23123149/27ef40dc-f75f-11e6-8ae6-4ef72bc78746.png)

**Steps to reproduce**
Click on the OFC Tab

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
JS IDE FOR ZEPHYR OS / v0.8.3-alpha / eb16de3

**Comment by siovene** [comment]
OCF Explorer is removed from the WebIDE, so I'm closing this issue for now.

**Comment by qiuzhong** [comment]
It's sensible since feature changed.
