### ISSUE TITLE
Compatibility message on not supported browsers

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#60]
**Issue description**
The message "Your browser does not support WebUSB" is not very visible, visually, and changes position according to the type of browser.

**Current behavior**
The message "Your browser does not support WebUSB" is not very visible, visually, and changes position according to the type of browser.
Safari:
![safari](https://cloud.githubusercontent.com/assets/1953388/23256614/1a8c73dc-f9b8-11e6-9863-8cd90448e69e.png)
Firefox:
![firefox](https://cloud.githubusercontent.com/assets/1953388/23256616/1c9565e4-f9b8-11e6-9d6f-ee29f30d520c.png)

**Expected behavior**
Consistent visual, and position cross browsers. we can use the error notification visual for this message, example:
![example](https://cloud.githubusercontent.com/assets/1953388/23256675/6c713552-f9b8-11e6-85c0-ae9705cfab9f.jpg)

**Steps to reproduce**
Open the editor in Safari, or Firefox

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`

**Comment by siovene** [comment]
Would it be okay to have that as a sticky notification, i.e. one that doesn't disappear by itself but only if closed by the user?

**Comment by clagom** [comment]
Yes I think so
