### ISSUE TITLE
"Board schematics" to "Board explorer"

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#62]
**Issue description**
Now the title says "Board schematics" but schematic in hardware means something like this kind of view:
![schematic](https://cloud.githubusercontent.com/assets/1953388/23261284/839ba55e-f9cd-11e6-8c92-3e7aa1017ae6.png)

**Current behavior**
"Board schematics"

**Expected behavior**
We can change to "Board explorer", as we use in other Intel's products websites

**Steps to reproduce**
Editor page

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
JS IDE FOR ZEPHYR OS / v0.9.0-alpha / a9cec59

**Comment by qiaojingx** [comment]
Verified with JS IDE FOR ZEPHYR OS / v0.9.0-alpha / 0e5e943.
"Board schematics" was changed to "Board explorer"
This issue is not reproducible
