### ISSUE TITLE
The app needs a nice logo and favicon

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#64]
It would be great to have a logo to feature in the landing page and perhaps the header.
A favicon is needed too.

@clagom would you look into it?

**Comment by clagom** [comment]
Sure, we're going to work on this.

**Comment by clagom** [comment]
This is for the favicon https://github.com/01org/zephyrjs-ide/issues/101
The logo is coming in proper formats too, we're working on the landing page and header modifications mockups
