### ISSUE TITLE
The e2e build is broken with regards to SCSS

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#65]
**Issue description**
`npm run serve.e2e` results in broken (404) CSS links. I suppose something's wrong with the SCSS adaptation there.

**Current behavior**
`npm run serve.e2e` cannot be used.

**Expected behavior**
`npm run serve.e2e` produces a working output.

**Steps to reproduce**
Run `npm run serve.e2e`.

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`0.10.0-alpha`

**Comment by qiuzhong** [comment]
Verified  with 0.13.0-alpha / [0d23d31](https://github.com/01org/zephyrjs-ide/commit/0d23d317cabe0147aef9324e617ef0d458a20f28). <code>npm run serve.e2e</code> works well now.
