### ISSUE TITLE
[UI] More than one tab display as highlight

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#68]
**Issue description**

More than one tab display as highlight

**Current behavior**

![selection_001](https://cloud.githubusercontent.com/assets/19813546/23849016/a6ab4c48-0814-11e7-91f6-563fa18f8c15.png)

**Expected behavior**

![selection_002](https://cloud.githubusercontent.com/assets/19813546/23849021/ab723cd2-0814-11e7-9c29-16236cc7a8f2.png)

**Steps to reproduce**

1. Create TAB#2 and TAB#3 by click "new tab"
2. Activate TAB#1 by click "TAB#1"
3. Close TAB#2 by click “X” on “TAB#2”

**'JS IDE for Zephyr OS' version:** `v0.10.1-alpha / 5f1ccc5`

**Comment by siovene** [comment]
Also reproducible by:

- Create Tab #2 
- Activate Tab #1 
- Create Tab #3

**Comment by qiaojingx** [comment]
Verified with JS IDE FOR ZEPHYR OS / v0.10.1-alpha / aadfc5e. This issue is not reproducible.
