### ISSUE TITLE
[UI] Button design is inconsistent

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#69]
**Issue description**

Button design is inconsistent

**Current behavior**

1. Button 1 and 3 are inconsistent if click GitHub in different tabs.
2. Other buttons are more square than button 2.  Is that better to keep button consistent?
![selection_010](https://cloud.githubusercontent.com/assets/19813546/23893992/7a8f34cc-08db-11e7-9ece-2c8dcb0097a4.png)
![selection_011](https://cloud.githubusercontent.com/assets/19813546/23893991/7a8ba762-08db-11e7-9a7a-a15646e89adf.png)

**Expected behavior**

Button design should be consistent.

**Steps to reproduce**

1. Create mutiple tabs. Click GitHub in TAB#1 and other tabs.

**'JS IDE for Zephyr OS' version:** `v0.10.1-alpha / 0725450`

**Comment by clagom** [comment]
Will work on these mockups as discussed today

**Comment by siovene** [comment]
For now I made all buttons round as the "New tab" and "Console" buttons. Will change later if a UI spec is released.

**Comment by clagom** [comment]
Sent the proposal for the GitHub UI, where we define also these UI elements for consistency

**Comment by qiaojingx** [comment]
Verified with v0.12.1-alpha / 7789490. This issue is not reproducible.
