### ISSUE TITLE
Layout modifications

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#71]
**Issue description**
As discussed, the console will move, remove OCF explorer

**Expected behavior**
![ide-sidebar-01a](https://cloud.githubusercontent.com/assets/1953388/23899581/9bfe065c-08ad-11e7-9355-f4b73455a6dd.jpg)
Please refer to the PDF we discussed for the overall flow: https://drive.google.com/open?id=0B8p6OLiPT_x5cXp6aUlEMmNzdVE

**Steps to reproduce**
Current layout

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
/ v0.10.1-alpha / 5f1ccc5

**Comment by siovene** [comment]
Already fixed a while ago, forgot to close this.
