### ISSUE TITLE
Action notifications, visual confirmations

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#72]
**Issue description**
Implementing the visual notifications for the actions like uploaded, running, saved, and so on

**Current behavior**
Not present

**Expected behavior**
![ide-notification-running](https://cloud.githubusercontent.com/assets/1953388/23899705/207654ac-08ae-11e7-8d3e-9f9061b6cc96.jpg)

![ide-notification](https://cloud.githubusercontent.com/assets/1953388/23899713/24e2abbc-08ae-11e7-89fb-8446790ef679.jpg)

**Steps to reproduce**
Current layout

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
/ v0.10.1-alpha / 5f1ccc5

**Comment by siovene** [comment]
Do we need a notification after saving the tab? Seems a bit redundant as you need to explicitly save and confirm. I would leave such notifications for things happening indirectly, or tasks needing a confirmation. Does it make sense?

**Comment by clagom** [comment]
Yes I agree, now that we have save and confirm this is no longer needed. Still keep it as UI elements for important information (green), error (the red we have), and the neutral grey for less important notifications.

**Comment by siovene** [comment]
> Yes I agree, now that we have save and confirm this is no longer needed

Closing then.
