### ISSUE TITLE
Menu sidebar

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#73]
**Issue description**
Feature

**Expected behavior**
![ide-sidebar-01a](https://cloud.githubusercontent.com/assets/1953388/23900064/a0efbb0e-08af-11e7-9706-a3d7560bb78b.jpg)

![ide-sidebar-01b](https://cloud.githubusercontent.com/assets/1953388/23900067/a58e0832-08af-11e7-93dc-107f94729f3b.jpg)

![ide-sidebar-01c](https://cloud.githubusercontent.com/assets/1953388/23900077/aa19d8d6-08af-11e7-9fc5-dd6e5379a470.jpg)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
/ v0.10.1-alpha / 5f1ccc5

**Comment by clagom** [comment]
Will implement the mocukps with the content for the other items as well

**Comment by siovene** [comment]
I closed this issue even tho some minor features are missing, like searching and sorting.
For the GitHub link in the sidebar, I'll wait for the UI spec.
