### ISSUE TITLE
[UI] Unable to resize again if console window enlarged to the max

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#78]
**Issue description**

Unable to resize again if console window enlarged to the max

**Current behavior**

Unable to resize again if console window enlarged to the max
![selection_022](https://cloud.githubusercontent.com/assets/19813546/24037815/f4f2d0ce-0b39-11e7-9b03-e29f88616efc.png)

**Expected behavior**

Resize ok

**Steps to reproduce**

1. Enlarge console window to the max like the pic.
2. Try to resize console window again. 

**'JS IDE for Zephyr OS' version:** `v0.11.0-alpha / fe0b8be`

**Comment by siovene** [comment]
I can't reproduce this, it seems to work fine for me. Are you able to provide more details?

**Comment by qiaojingx** [comment]
![selection_023](https://cloud.githubusercontent.com/assets/19813546/24038352/f77be518-0b3b-11e7-85e6-735ff02fb630.png)
![selection_024](https://cloud.githubusercontent.com/assets/19813546/24038362/fc30b930-0b3b-11e7-95c8-605e0286fe4d.png)
Click and drag frame from position 1.  Click again to fix when move frame to position 2.
Then i will unable to resize it again unless to clear browser history.

**Comment by siovene** [comment]
I still can't reproduce. Please look at the following video: https://youtu.be/kcYP9BfuZ80
Am I missing something?

**Comment by qiaojingx** [comment]
This issue is reproduced by https://01org.github.io/zephyrjs-ide/#/editor. Sorry for missing this information. Could you please try again?
Here is my issue behavior:
https://youtu.be/AK2qXwvxGXg

**Comment by qiaojingx** [comment]
Verified with JS IDE FOR ZEPHYR OS / v0.11.2-alpha / b07fb43. This issue is not reproducible.
