### ISSUE TITLE
GitHub integration - Updated UI

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#79]
**Issue description**
New GitHub UI implementation

**Expected behavior**
[IDE-GitHub-flow.pdf](https://github.com/01org/zephyrjs-ide/files/872531/IDE-GitHub-flow.pdf)

**Steps to reproduce**
GitHub integration process, select repository, select branch

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.12.1-alpha / 592fc72

**Comment by clagom** [comment]
Working on the UI, but noticed this small bug

**Comment by siovene** [comment]
Waiting for the updated UI spec before looking at this.

**Comment by clagom** [comment]
Changed this for the new UI
