### ISSUE TITLE
Board viewer > Board explorer

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#80]
**Issue description**
"Board viewer" should be "Board explorer"

**Current behavior**
It's called "Board viewer"

**Expected behavior**
"Board explorer" title

**Steps to reproduce**

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.11.1-alpha / 9c4383c

**Comment by qiaojingx** [comment]
Verified with JS IDE FOR ZEPHYR OS / v0.11.2-alpha / f5f131e. This issue is not reproducible.
