### ISSUE TITLE
Device disconnected automatically if plugin a second device

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#82]
**Issue description**

Device disconnected automatically if plugin a second device

**Current behavior**

Device disconnected automatically from WebIDE if plugin a second device
![selection_006](https://cloud.githubusercontent.com/assets/19813546/24135729/68636924-0e46-11e7-9367-b08131f4e191.png)

**Expected behavior**

Plugging the second device shouldn't effect the connection of the first device.

**Steps to reproduce**

1. Plugin A101 to PC and connect it to TAB#1.
2. Plugin another A101 to PC

**'JS IDE for Zephyr OS' version:** `JS IDE FOR ZEPHYR OS / v0.11.2-alpha / f5f131e`

**Comment by qiuzhong** [comment]
I cannot reproduce this in recently tests.
