### ISSUE TITLE
[UI] Scrollbar of editor windows doesn’t follow frame closely

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#83]
**Issue description**

Scrollbar of editor windows doesn’t follow frame closely

**Current behavior**

Scrollbar of editor windows doesn’t follow frame closely when click and drag the frame
![screenshot from 2017-03-22 10-47-11](https://cloud.githubusercontent.com/assets/19813546/24180190/7314372e-0eee-11e7-9cc0-a71bb7477cea.png)

**Expected behavior**

Scrollbar of editor windows always follow frame closely

**Steps to reproduce**

1. Input some code in editor windows make sure scrollbar show up.
2. Click and drag frame between editor and console windows.

**'JS IDE for Zephyr OS' version:** `v0.11.2-alpha / f5f131e`

**Comment by siovene** [comment]
Did you take that screenshot after you stopped moving the resize handle, or at the same time while you were still moving it very fast?

**Comment by qiaojingx** [comment]
At the same time while I am still moving it.

**Comment by siovene** [comment]
Then I'm afraid there's nothing we can do about it. Besides, it's a very, very minor issue.
