### ISSUE TITLE
Footer modification

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#85]
**Issue description**
As discussed, footer modifications: remove the title, move the links aligned with the title in the header.

**Current behavior**
![screen shot 2017-03-23 at 12 16 15](https://cloud.githubusercontent.com/assets/1953388/24247290/00cdd33e-0fc3-11e7-8f4d-7ba2c347a6c2.png)

**Expected behavior**
<img width="340" alt="screen shot 2017-03-23 at 12 17 07" src="https://cloud.githubusercontent.com/assets/1953388/24247294/043aa75e-0fc3-11e7-93be-1070f6c92b38.png">

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.8.3-alpha / eb16de3

**Comment by siovene** [comment]
The title is already removed and the links are aligned. Do you want me to make them smaller and grey?

**Comment by clagom** [comment]
If possible with the next release yes, please. I think they look a bit too visible now, not primary action (like the green we use). Font size can be the same, mainly a colour change, thanks
