### ISSUE TITLE
gutters between panels too thick

### ISSUE THREAD

**Issue by AdamCrickett** [01org/zephyrjs-ide#86]
**Issue description**
The gutters between windows are currently too thick, they look too heavy.

**Current behavior**
Current thickness is 7px

**Expected behavior**
Change thickness to 3px

**Steps to reproduce**

**'JS IDE for Zephyr OS' version:** v0.12.0-alpha / d84461b

**Comment by siovene** [comment]
At `3px` I find it too hard to grab for resizing. I can have a thicker invisible overlay that does the actual resizing but I need to patch an external component.

**Comment by siovene** [comment]
PR to external component submitted. https://github.com/wannabegeek/ng2-split-pane/pull/16
