### ISSUE TITLE
Proposal: forego the capital letters in tab titles

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#91]
**Issue description**
Capital letters in tab titles are confusing, because tab titles are somewhat related to filenames when saving the contents of a tab, and they are suggested as a default value when clicking on the `Save` button and the tab title is not in the form of `Tab # x`.

**Current behavior**
The user is confused by the fact that the tab title has all capital letters, while the filename doesn't, yet they are treated as equal (e.g. "MY FILE" vs "My file")

**Expected behavior**
The user sees what the user types.

@clagom do you think we can do this?

**Comment by clagom** [comment]
+1 I think your point makes sense in the tabs/filenames, yes.
