### ISSUE TITLE
Most tests aren't running because the syntax in the hardcoded examples messes up with the linter/compiler

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#97]
**Issue description**

Not all tests are running.

**Current behavior**

`npm test` results in warnings and errors about failing imports that are actually hardcoded strings for the examples.

**Expected behavior**

All specs run.

**Steps to reproduce**

`npm test`

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`

d0575587f23b8b31a78f17f3d36ddece843dc7f9

**Comment by qiaojingx** [comment]
Verified with commit 208a971 in update-seed branch and 0d23d31 in master. This issue is not reproduced.
